# Generated by Django 4.0.3 on 2022-05-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articulo',
            table=None,
        ),
    ]
